let frutas = ["maçã", "banana", "laranja"];
console.log("Frutas iniciais:", frutas);
console.log("Segundo elemento:", frutas[1]);
frutas.push("morango");
console.log("Após adicionar morango:", frutas);
frutas.shift();
console.log("Após remover o primeiro elemento:", frutas);
let numeros = [10, 20, 30, 40];
console.log("Números iniciais:", numeros);
numeros.push(50);
console.log("Após push:", numeros);
numeros.pop();
console.log("Após pop:", numeros);
numeros.unshift(5);
console.log("Após unshift:", numeros);
numeros.shift();
console.log("Após shift:", numeros);
let frutas2 = ["manga", "abacaxi", "melancia"];
let todasFrutas = frutas.concat(frutas2);
console.log("Todas as frutas:", todasFrutas);
let primeirasFrutas = todasFrutas.slice(0, 2);
console.log("Duas primeiras frutas:", primeirasFrutas);
todasFrutas.splice(1, 1);
console.log("Após remover o segundo elemento:", todasFrutas);
let indiceBanana = todasFrutas.indexOf("banana");
console.log("Índice da banana:", indiceBanana);
let frutasComM = todasFrutas.filter(fruta => fruta.startsWith("m"));
console.log("Frutas com 'm':", frutasComM);
let numerosDobrados = numeros.map(num => num * 2);
console.log("Números dobrados:", numerosDobrados);
console.log("Todas as frutas (forEach):");
todasFrutas.forEach(fruta => console.log(fruta));
